language: generic 
sudo: required
services:
  - docker

before_install:
  - docker build -t lukasjvdm/docker-react -f Dockerfile.dev .

script:
  - docker run -e CI=true lukasjvdm/docker-react npm run test