    name: Deploy MultiDocker
    on:
      push:
        branches:
          - main
     
    jobs:
      build:
        runs-on: ubuntu-latest
        steps:
          - uses: actions/checkout@v2
          - run: docker login -u ${{ secrets.DOCKER_USERNAME }} -p ${{ secrets.DOCKER_PASSWORD }}
          - run: docker build -t lukasjvdm/docker-react -f ./Dockerfile.dev ./
          - run: docker run -e CI=true lukasjvdm/docker-react npm test
     
          - run: docker build -t lukasjvdm/multi-client-10-14 ./
          - run: docker build -t lukasjvdm/multi-nginx-10-14 ./nginx
          - run: docker build -t lukasjvdm/multi-server-10-14 ./server
          - run: docker build -t lukasjvdm/multi-worker-10-14 ./worker
     
          - run: docker push lukasjvdm/multi-client-10-14
          - run: docker push lukasjvdm/multi-nginx-10-14
          - run: docker push lukasjvdm/multi-server-10-14
          - run: docker push lukasjvdm/multi-worker-10-14
     
          - name: Generate deployment package
            run: zip -r deploy.zip . -x '*.git*'
     
          - name: Deploy to EB
            uses: einaregilsson/beanstalk-deploy@v18
            with:
              aws_access_key: ${{ secrets.AWS_ACCESS_KEY }}
              aws_secret_key: ${{ secrets.AWS_SECRET_KEY }}
              application_name: docker-react
              environment_name: Dockerreact-env
              existing_bucket_name: elasticbeanstalk-eu-west-2-501640355287
              region: eu-west-2
              version_label: ${{ github.sha }}
              deployment_package: deploy.zip